# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2571da6b6be3a135b1d27de7addc9ae8d83eeb52bef66d0af7bde7d93ab95fe6baf9cc6cd16419ab2c92bf650374230a36f42c2b267ee47c82138c6f11a411dc

test:
  secret_key_base: f8798aabafd90ac60573837a01cade501c1240d519bc72d34116befeadcb79909f4b960ac923a16c1ef07a219f307b60d72f1a97657245145a089167f75b1f3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
